name: Build Airsim

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: make
      run: ./build.cmd
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        path: ./Unreal/Plugins
